name: Detox E2E CI

on:
  pull_request:
    branches:
      - "*"
  workflow_dispatch:
    inputs:
      prNumber:
        description: pr number to trigger on
        required: true

jobs:
  # prepare-test-run:
  #   name: "Prepare test run"
  #   runs-on: macos-latest
  #   steps:
  #     - name: prepare runner
  #       run: 

  ios:
    # needs: [prepare-test-run]
    runs-on: macos-latest
    steps:
      - name: Checkout PR
        uses: actions/checkout@v2
        with:
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6 # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - name: Install applesimutils
        run: |
          brew tap wix/brew
          brew install applesimutils

      - name: Get yarn cache
        id: get-yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Check cache
        id: check-yarn-cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.get-yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Setup Node
        if: steps.check-yarn-cache.outputs.cache-hit != 'true'
        uses: actions/setup-node@main
        with:
          node-version: 14.x

      # - name: Install dependencies
      #   if: steps.check-yarn-cache.outputs.cache-hit != 'true'  
      #   run: yarn install

      - name: Has hash commit deps
        uses: ledgerhq/actions/packages/has-hash-commit-deps@main
        id: has-hash-commit-deps
        with:
          workspace: ${{ github.workspace }}

      - name: install dependencies
        if: ${{ steps.has-hash-commit-deps.outputs.has-hash-commit-deps == 'true' }}
        env:
          JOBS: max
        run: yarn --frozen-lockfile --network-timeout 100000 --network-concurrency 1

      - name: install dependencies
        if: ${{ steps.has-hash-commit-deps.outputs.has-hash-commit-deps == 'false' }}
        env:
          JOBS: max
        run: yarn --frozen-lockfile --network-timeout 100000

      - name: Rebuild detox
        if: steps.check-yarn-cache.outputs.cache-hit == 'true'
        run: detox clean-framework-cache && detox build-framework-cache

      - name: Build iOS app for detox test run
        run: yarn detox build -c ios.staging

      - name: Test iOS app
        run: yarn start & yarn detox test -c ios.staging --loglevel verbose --record-logs failing --record-timeline all --take-screenshots failing --retries 1 --reuse --cleanup

      - name: upload test artifacts
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-artifacts
          path: |
            e2e/artifacts
        
  android:
    runs-on: macos-latest
    steps:
      - name: Checkout PR
        uses: actions/checkout@v2
        with:
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}

      - name: Get yarn cache
        id: get-yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Check cache
        id: check-yarn-cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.get-yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Setup Node
        if: steps.check-yarn-cache.outputs.cache-hit != 'true'
        uses: actions/setup-node@main
        with:
          node-version: 14.x

      - name: Check Gradle Cache
        uses: actions/cache@v2
        id: gradle-cache
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: has hash commit deps
        uses: ledgerhq/actions/packages/has-hash-commit-deps@main
        id: has-hash-commit-deps
        with:
          workspace: ${{ github.workspace }}

      - name: install dependencies
        if: ${{ steps.has-hash-commit-deps.outputs.has-hash-commit-deps == 'true' }}
        env:
          JOBS: max
        run: yarn --frozen-lockfile --network-timeout 100000 --network-concurrency 1

      - name: install dependencies
        if: ${{ steps.has-hash-commit-deps.outputs.has-hash-commit-deps == 'false' }}
        env:
          JOBS: max
        run: yarn --frozen-lockfile --network-timeout 100000      

      # - name: Install node dependencies
      #   if: steps.check-yarn-cache.outputs.cache-hit != 'true'
      #   run: yarn install --frozen-lockfile
      
      - name: Build Android app for Detox test run
        run: yarn detox build -c android.staging-ci

      - name: Test Android app (with Test Butler)
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          avd-name: Pixel_XL_API_30
          script: |
            mkdir ./temp
            curl -f -o ./temp/test-butler-app.apk https://repo1.maven.org/maven2/com/linkedin/testbutler/test-butler-app/2.2.1/test-butler-app-2.2.1.apk
            adb install ./temp/test-butler-app.apk || adb install ./e2e/test-butler-app.apk
            yarn start & yarn detox test -c android.staging-ci  --loglevel verbose --record-logs failing --record-timeline all --take-screenshots failing --retries 1 --reuse --cleanup
            
      - name: upload test artifacts
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-artifacts
          path: |
            e2e/artifacts
